{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry-dns-switcher.secretName" . }}
  labels:
    {{- include "registry-dns-switcher.labels" . | nindent 4 }}
type: Opaque
stringData:
  VICTORIA_METRICS_BEARER_TOKEN: {{ .Values.secret.victoriaMetrics.bearerToken | quote }}
  VICTORIA_METRICS_BASIC_AUTH_USERNAME: {{ .Values.secret.victoriaMetrics.basicAuth.username | quote }}
  VICTORIA_METRICS_BASIC_AUTH_PASSWORD: {{ .Values.secret.victoriaMetrics.basicAuth.password | quote }}
  CLOUDFLARE_API_TOKEN: {{ .Values.secret.cloudflare.apiToken | quote }}
  CLOUDFLARE_ZONE_ID: {{ .Values.secret.cloudflare.zoneId | quote }}
  ALIYUN_ACCESS_KEY_ID: {{ .Values.secret.alidns.accessKeyId | quote }}
  ALIYUN_ACCESS_KEY_SECRET: {{ .Values.secret.alidns.accessKeySecret | quote }}
{{- end }}
